import { create } from "zustand";

export type TestId = "test1" | "test2";

export type McqQuestion = {
  id: string;
  testId: TestId;
  type: "mcq";
  question: string;
  options: string[];
  /** Single string for single-answer MCQs; array for multi-select. */
  answer: string | string[];
  explanation: string;
};

export type TextQuestion = {
  id: string;
  testId: TestId;
  type: "text";
  question: string;
  sample: string;
};

export type Question = McqQuestion | TextQuestion;

export const TESTS: { id: TestId; title: string; subtitle: string }[] = [
  {
    id: "test1",
    title: "Test 1 — PM Foundations",
    subtitle: "24 câu hỗn hợp: PM, UX, Data, Fintech.",
  },
  {
    id: "test2",
    title: "Test 2 — H4TF: PM 2025",
    subtitle: "Trắc nghiệm + tự luận từ bộ đề Heading for the Future.",
  },
];

const mcq = (
  testId: TestId,
  id: string,
  question: string,
  options: string[],
  correct: number | number[],
  explanation = "",
): McqQuestion => ({
  id,
  testId,
  type: "mcq",
  question,
  options,
  answer: Array.isArray(correct) ? correct.map((i) => options[i]) : options[correct],
  explanation,
});

const text = (
  testId: TestId,
  id: string,
  question: string,
  sample: string,
): TextQuestion => ({
  id,
  testId,
  type: "text",
  question,
  sample,
});

const seedTest1: Question[] = [
  mcq("test1",
    "q1",
    "Câu 1: Đâu là mô tả chính xác nhất về vai trò cốt lõi của Product Manager trong một Product Team?",
    [
      "A. Viết code cho các tính năng quan trọng nhất của sản phẩm để đảm bảo chất lượng kỹ thuật",
      "B. Quản lý timeline và phân công công việc cho từng thành viên trong team",
      "C. Xác định vấn đề người dùng cần giải quyết, ưu tiên các giải pháp và align team hướng đến mục tiêu sản phẩm",
      "D. Thiết kế giao diện và trải nghiệm người dùng cho từng tính năng mới",
    ],
    2,
    "PM tập trung vào user problem, prioritization và product direction thay vì coding hay quản lý task.",
  ),
  mcq("test1",
    "q2",
    "Câu 2: Trong Agile/Scrum, Product Backlog khác với Sprint Backlog ở điểm nào?",
    [
      "A. Product Backlog chỉ dành cho Product Owner còn Sprint Backlog là của cả team",
      "B. Product Backlog chứa tất cả bug cần sửa, Sprint Backlog chứa tính năng mới cần build",
      "C. Product Backlog là danh sách toàn bộ công việc của sản phẩm theo thứ tự ưu tiên; Sprint Backlog là tập con được chọn để hoàn thành trong một sprint cụ thể",
      "D. Product Backlog không cần sắp xếp thứ tự ưu tiên vì mọi item đều quan trọng như nhau",
    ],
    2,
    "Sprint Backlog là tập con của Product Backlog cho sprint hiện tại.",
  ),
  mcq("test1",
    "q3",
    'Câu 3: Một PM đang nghiên cứu lý do tại sao người dùng bỏ qua bước "Tạo hồ sơ cá nhân" trong onboarding của ứng dụng tài chính. Phương pháp nào dưới đây giúp xác định nguyên nhân gốc rễ tốt nhất?',
    [
      "A. Xem báo cáo phân tích tỷ lệ hoàn thành từng bước trong funnel onboarding",
      'B. Phỏng vấn người dùng bằng kỹ thuật "5 Whys" để khám phá lý do thực sự đằng sau hành vi bỏ qua bước đó',
      "C. Gửi khảo sát hỏi người dùng có thích tính năng tạo hồ sơ không",
      "D. So sánh tỷ lệ bỏ qua bước này với benchmark của ứng dụng tài chính cùng phân khúc",
    ],
    1,
    "5 Whys giúp đào sâu từ hành vi bề mặt xuống root cause.",
  ),
  mcq("test1",
    "q4",
    "Câu 4: Người dùng phàn nàn rằng họ không tìm được tài xế vào giờ cao điểm. Đâu là cách phát biểu vấn đề (problem statement) lấy người dùng làm trung tâm đúng nhất?",
    [
      "A. Hệ thống phân bổ tài xế cần được tối ưu hóa bằng thuật toán AI để giảm thời gian chờ",
      "B. Người dùng đi làm cần đảm bảo di chuyển đúng giờ, nhưng họ thường xuyên không đặt được xe trong giờ cao điểm, khiến họ lo lắng và trễ hẹn",
      "C. Số lượng tài xế hoạt động trong giờ cao điểm thấp hơn 30% so với nhu cầu thực tế của thị trường",
      "D. Tỷ lệ huỷ chuyến trong giờ cao điểm tăng 15% so với quý trước, ảnh hưởng đến doanh thu",
    ],
    1,
    "Problem statement user-centric mô tả người dùng, nhu cầu và pain point thực tế.",
  ),
  mcq("test1",
    "q5",
    "Câu 5: Trong quá trình phát triển sản phẩm, User empathy đóng vai trò cốt lõi nhất là gì đối với một Product Manager?",
    [
      "A. Giúp PM thu thập và lập trình chính xác 100% các tính năng theo đúng yêu cầu người dùng đưa ra",
      "B. Giúp PM thao túng tâm lý người dùng để tăng Conversion Rate mua hàng",
      "C. Giúp PM đặt mình vào bối cảnh thực tế của người dùng để đào sâu tìm ra root cause và nhu cầu ẩn sâu, thay vì chỉ giải quyết các vấn đề bề mặt mà người dùng nói ra",
      "D. Giúp PM nhượng bộ các yêu cầu của khách hàng và thay đổi Product Roadmap liên tục",
    ],
    2,
    "Empathy giúp PM hiểu nhu cầu ẩn, không chỉ làm theo yêu cầu bề mặt.",
  ),
  mcq("test1",
    "q6",
    "Câu 6: Double Diamond Framework mang lại những tác dụng cốt lõi nào cho Product Team? (Chọn nhiều phương án)",
    [
      "A. Giúp team tách biệt rõ ràng giữa việc tìm ra Đúng vấn đề cần giải quyết và việc xây dựng Đúng giải pháp",
      "B. Là một framework quản lý tiến độ dự án thay thế hoàn toàn cho Agile/Scrum",
      "C. Khuyến khích sự luân phiên giữa tư duy phân kỳ và tư duy hội tụ ở cả pha nghiên cứu lẫn thiết kế",
      "D. Ngăn chặn tình trạng PM nhảy ngay vào chốt tính năng khi chưa hiểu rõ nhu cầu gốc rễ của người dùng",
      "E. Cung cấp bộ công cụ tự động hóa để dự báo chính xác doanh thu và CAC trước khi sản phẩm ra mắt",
    ],
    [0, 2, 3],
    "Double Diamond là framework tư duy phân kỳ/hội tụ tách problem space và solution space.",
  ),
  mcq("test1",
    "q7",
    "Câu 7: Ví điện tử có 65% người dùng thoát app tại màn hình eKYC. Metrics nào quan trọng nhất cần kiểm tra ngay? (Chọn nhiều phương án)",
    [
      "A. Customer Acquisition Cost (CAC)",
      "B. API Error Rate / Timeout Rate của hệ thống OCR",
      "C. Net Promoter Score (NPS)",
      'D. Permission Denial Rate (Tỷ lệ người dùng bấm "Từ chối" cấp quyền Camera)',
      "E. Average Revenue Per User (ARPU)",
    ],
    [1, 3],
    "Drop-off tại eKYC thường do lỗi kỹ thuật OCR hoặc từ chối cấp quyền camera.",
  ),
  mcq("test1",
    "q8",
    "Câu 8: SaaS dùng Per-seat pricing, khách hàng dùng chung tài khoản để tiết kiệm. Cạm bẫy lớn nhất của mô hình giá này là gì?",
    [
      "A. Khó tính toán doanh thu định kỳ (MRR)",
      "B. Trở thành rào cản tài chính khiến khách hàng hạn chế số người dùng mới, làm phần mềm khó phổ biến rộng rãi",
      "C. Không thể thu tiền qua thẻ tín dụng",
      "D. Server sẽ bị quá tải nhanh hơn",
    ],
    1,
    "Per-seat tạo rào cản mở rộng adoption trong tổ chức.",
  ),
  mcq("test1",
    "q9",
    "Câu 9: Khác biệt lớn nhất về nguồn doanh thu cốt lõi của BNPL so với thẻ tín dụng truyền thống là gì?",
    [
      "A. BNPL chủ yếu kiếm lợi nhuận từ phí thường niên từ người mua",
      "B. Doanh thu cốt lõi của BNPL đến từ Merchant Discount Rate thu từ người bán; người mua thường được miễn lãi nếu trả đúng hạn",
      "C. Cả hai giống nhau, BNPL vẫn kiếm tiền 100% từ lãi suất người tiêu dùng",
      "D. BNPL yêu cầu người dùng nạp cọc cố định trước khi mua sắm",
    ],
    1,
    "BNPL kiếm tiền từ merchant fee, khác credit card kiếm từ interest người dùng.",
  ),
  mcq("test1",
    "q10",
    "Câu 10: Tại app du lịch, DAU = số user tìm chuyến bay hoặc xem phòng khách sạn trong ngày. Tại sao chỉ số này quan trọng?",
    [
      "A. Đo lường mức độ tương tác cốt lõi hàng ngày và nhu cầu tìm hiểu du lịch của người dùng",
      "B. Phản ánh trực tiếp tổng doanh thu đặt vé/đặt phòng hàng tháng",
      "C. Chỉ tính những người dùng đã thanh toán thành công trong ngày",
      "D. Dùng để thay thế hoàn toàn cho Retention Rate và LTV",
    ],
    0,
    "DAU đo intent và engagement core, không phải doanh thu trực tiếp.",
  ),
  text("test1", "q11",
    "Câu 11 (50-100 chữ): Sự khác biệt giữa output và outcome trong quản lý sản phẩm là gì? Lấy một ví dụ cụ thể để minh họa.",
    "Output là thứ team build/release (feature, bản update). Outcome là thay đổi hành vi hoặc giá trị thực tế mà output đó tạo ra. Ví dụ: ra mắt nút 'one-click reorder' là output; outcome là tỷ lệ repeat order tăng 20%.",
  ),
  text("test1", "q12",
    'Câu 12 (150-200 chữ): Viết user story hoàn chỉnh cho tính năng "Lưu địa chỉ giao hàng" và nêu ít nhất 2 acceptance criteria.',
    'User story: "Là một người dùng thường xuyên đặt đồ ăn, tôi muốn lưu nhiều địa chỉ giao hàng, để không phải nhập lại mỗi lần đặt." AC: "Người dùng có thể lưu tối đa 5 địa chỉ.", "Địa chỉ đã lưu xuất hiện trong dropdown khi checkout."',
  ),
  text("test1", "q13",
    "Câu 13 (50-100 chữ): App học tiếng Anh có DAU tăng 15% nhưng số bài học hoàn thành/người giảm từ 3 xuống 2. Dữ liệu nói lên điều gì về chất lượng tăng trưởng?",
    "DAU tăng nhưng engagement per user giảm — có thể do nguồn user mới kém chất lượng hoặc onboarding bị suy giảm. Nên lo ngại vì có thể là 'vanity growth'.",
  ),
  text("test1", "q14",
    "Câu 14 (150-200 chữ): Reorder feature có usage 18% nhưng completion 40% (vs 72% luồng thường). Đặt 2 giả thuyết và 1 cách kiểm chứng cho mỗi giả thuyết.",
    "GT1: Đơn cũ chứa item hết hàng/đổi giá → query % đơn reorder bị block out-of-stock và so giá. GT2: User dùng reorder để xem lại rồi sửa → session recording + funnel.",
  ),
  text("test1", "q15",
    "Câu 15 (200-250 chữ): Shopee CR giảm 3.2%→2.7%, Mobile giảm 3.0%→2.2%, Desktop ổn định. Checkout Mobile load time 1.8s→3.4s sau update app. Vấn đề chính, 2 hành động, 1 metric.",
    "Root cause: update app làm chậm checkout Mobile, gây drop-off. Ngắn hạn: rollback. Dài hạn: performance budget + monitoring. Metric: Mobile checkout load time và Mobile CR.",
  ),
  text("test1", "q16",
    "Câu 16 (200-250 chữ): App Mobile Banking update thành Super App, rating 4.6→3.2, chuyển tiền 15s→45s. 3 nguyên nhân chính.",
    "1) Phá vỡ thói quen (broken mental model). 2) Quá tải nhận thức (cognitive overload). 3) Thiếu chiến lược chuyển đổi giao diện (no tutorial, no opt-out).",
  ),
  text("test1", "q17",
    "Câu 17 (200-250 chữ): ChatGPT Plus conversion giảm 25%, churn tăng 20%, không downtime, vừa update model. 2 giả thuyết + kiểm chứng.",
    "GT1: Model mới khiến Free 'đủ tốt' → so rate-limit Free trước/sau. GT2: Model mới giảm chất lượng use case Plus → thumbs-down rate theo use case + cancel survey.",
  ),
  text("test1", "q18",
    "Câu 18 (nối tiếp Câu 17): Hành động ngắn hạn.",
    "Free: tinh chỉnh rate-limit. Plus: giữ model legacy, email re-engagement, retain coupon, log feedback tại cancel.",
  ),
  text("test1", "q19",
    'Câu 19 (100-150 chữ): Giải thích "Feature Factory" và tác hại.',
    "Feature Factory: đo thành công bằng số feature ship thay vì giá trị. Tác hại: không đo outcome, debt tăng, team mất động lực, sản phẩm cồng kềnh.",
  ),
  text("test1", "q20",
    "Câu 20 (150-200 chữ): PM mới gia nhập team Feature Factory, làm gì để dịch chuyển tư duy?",
    "Gắn initiative với outcome metric; discovery trước delivery; post-launch review; kill feature không impact.",
  ),
  text("test1", "q21",
    "Câu 21 (100-150 chữ): AI Agent Telesale tiếng Anh bị troll. Tinh chỉnh System Prompt thế nào?",
    "(1) Định danh nhân viên tư vấn. (2) Nhiệm vụ rõ. (3) Guardrails: từ chối off-topic, lái về khóa học. (4) Tone & format. (5) Fallback.",
  ),
  text("test1", "q22",
    "Câu 22 (100-150 chữ): SaaS Day-1 Retention thấp. Time-to-Value, Aha! Moment, 2 giải pháp UX rút ngắn TTV.",
    "Aha: tạo và hoàn thành task đầu cùng team. TTV: từ signup → Aha. (1) Template preloaded. (2) Interactive checklist + mời teammate sớm.",
  ),
  text("test1", "q23",
    "Câu 23 (150-200 chữ): Chuyển khoản 20tr bị treo, tiền đã trừ, app báo 'Lỗi 404'. Thiết kế lại UX Writing và UI flow.",
    "Đổi sang thông báo trấn an + mã giao dịch. Icon vàng đồng hồ. Timeline 3 bước. CTA 'Theo dõi giao dịch'. Push notification cập nhật trạng thái.",
  ),
  text("test1", "q24",
    "Câu 24 (150-200 chữ): AI Agent code chậm 15-20s/response. Xử lý 'High Latency' bằng UX/UI.",
    "(1) Streaming token. (2) Skeleton + status text mô phỏng tư duy. (3) Disable Send + cancel button. (4) Set expectation '15-20s' khi submit.",
  ),
];

const seedTest2: Question[] = [
  // ===== PHẦN TRẮC NGHIỆM =====
  // PHẦN 1: GENERAL KNOWLEDGE
  mcq("test2", "t2-q1",
    "Câu 1: Trong quá trình phát triển sản phẩm, Product Manager cần sử dụng phương pháp nào để ưu tiên các tính năng nên phát triển trước?",
    ["A. MoSCoW", "B. PESTEL", "C. Lean Canvas", "D. SMART"],
    0,
    "MoSCoW (Must/Should/Could/Won't) là framework ưu tiên feature phổ biến.",
  ),
  mcq("test2", "t2-q2",
    "Câu 2: Đâu là ý đúng về Design Thinking? (Chọn nhiều phương án)",
    [
      "A. Một kỹ thuật thiết kế chuyên sâu dành cho người thiết kế đồ họa",
      "B. Gồm 5 bước: Define → Empathize → Ideate → Prototype → Test",
      "C. Một phương pháp sáng tạo để giải quyết vấn đề và phát triển giải pháp dựa trên nhu cầu người dùng",
      "D. Design Thinking chỉ dành cho người đứng đầu Product Team",
    ],
    [1, 2],
    "Design Thinking là framework giải quyết vấn đề user-centric, gồm 5 bước.",
  ),
  mcq("test2", "t2-q3",
    "Câu 3: Trong quá trình lên ý tưởng sản phẩm, Product Manager cần (Chọn nhiều phương án)",
    [
      "A. Thu thập insights và pain points người dùng trước để đưa ra những tính năng cần thiết và phù hợp",
      "B. Thiết kế một tính năng mới lạ, đột phá rồi phân tích xem tính năng đó sẽ giúp được người dùng như thế nào",
      "C. Tập trung vào việc tạo ra một sản phẩm với giao diện hấp dẫn và đẹp mắt trước tiên, sau đó mới tính đến chức năng của sản phẩm",
      "D. Nghiên cứu các sản phẩm của đối thủ cạnh tranh và học hỏi những tính năng thành công của họ để đảm bảo sản phẩm của mình có thể cạnh tranh trên thị trường",
    ],
    [0, 3],
    "Insights user + benchmark đối thủ là 2 input quan trọng cho ideation.",
  ),
  // PHẦN 3: UX/UI
  mcq("test2", "t2-q15",
    "Câu 15: Khi nào nên dùng Usability Testing thay vì A/B Testing? (Chọn nhiều phương án)",
    [
      "A. Muốn đo lường trực tiếp trải nghiệm người dùng với prototype mới",
      "B. Cần xác định yếu tố nào trên giao diện gây khó hiểu nhất",
      "C. Muốn so sánh hai biến thể hoàn thiện trên lượng lớn người dùng thực tế",
      "D. Khi có dữ liệu phân tích web (analytics) rõ ràng để đo lường",
    ],
    [0, 1],
    "Usability Testing dùng cho qualitative insight; A/B Test dùng cho quantitative comparison.",
  ),
  mcq("test2", "t2-q16",
    "Câu 16: Chọn các phương pháp User Testing có thể thực hiện từ xa (remote). (Chọn nhiều phương án)",
    [
      "A. Lab-based Testing",
      "B. Unmoderated Remote Testing",
      "C. Tree Testing",
      "D. Guerilla Testing",
      "E. Moderated Remote Testing",
    ],
    [1, 2, 4],
    "Lab-based và Guerilla cần gặp trực tiếp; còn lại có thể chạy remote.",
  ),
  mcq("test2", "t2-q17",
    'Câu 17: Khi triển khai bước "Research", bạn sẽ làm gì? (Chọn nhiều phương án)',
    [
      "A. Phỏng vấn người dùng",
      "B. Đọc báo cáo analytics",
      "C. Tạo flowchart",
      "D. Viết user-persona",
      "E. Thiết kế giao diện hi-fidelity",
    ],
    [0, 1, 3],
    "Research = phỏng vấn, đọc data, build persona. Flowchart/hi-fi thuộc design phase.",
  ),
  mcq("test2", "t2-q18",
    'Câu 18: Trong bước "Ideation", công cụ nào sau đây thường được dùng?',
    [
      "A. Affinity Diagram",
      "B. Heatmap Analytics",
      "C. Usability Report",
      "D. A/B Testing",
    ],
    0,
    "Affinity Diagram nhóm idea/insight trong ideation.",
  ),
  mcq("test2", "t2-q19",
    "Câu 19: Tiêu chí nào sau đây giúp đánh giá một sản phẩm có UI tốt? (Chọn nhiều phương án)",
    [
      "A. Màu sắc hài hòa, tương phản đủ",
      "B. Font size nhất quán",
      "C. Tỷ lệ Task Success > 90%",
      "D. Khoảng cách padding/margin đều",
      "E. Biểu tượng (icon) dễ hiểu",
    ],
    [0, 1, 3, 4],
    "Task Success thuộc UX/usability metric, không phải tiêu chí UI thuần.",
  ),
  // PHẦN 4: DATA
  mcq("test2", "t2-q23",
    "Câu 23: Khi phân tích hiệu quả một tính năng mới, bạn sẽ ưu tiên chỉ số nào nhất?",
    [
      "A. Tổng số lượt tải xuống/ sử dụng",
      "B. Tỷ lệ người dùng hoàn thành flow chính",
      "C. Số lượt chia sẻ trên mạng xã hội",
      "D. Thời gian trung bình dùng app",
    ],
    1,
    "Flow completion rate phản ánh trực tiếp trải nghiệm người dùng thực tế.",
  ),
  mcq("test2", "t2-q24",
    "Câu 24: Metric nào KHÔNG nên dùng để đánh giá một loyalty program?",
    [
      "A. Số điểm thưởng được tích lũy",
      "B. Tỷ lệ user đổi quà (Redemption Rate)",
      "C. Số lượt đăng nhập hàng ngày (DAU)",
      "D. Doanh thu từ user tham gia chương trình",
    ],
    2,
    "DAU không đo lường trực tiếp hiệu quả loyalty.",
  ),
  mcq("test2", "t2-q26",
    "Câu 26: Kết quả A/B test cho thấy phiên bản mới làm tăng 10% thời gian dùng app, nhưng giảm 5% doanh thu. Bạn sẽ:",
    [
      "A. Rollback ngay vì doanh thu quan trọng hơn",
      "B. Tiếp tục test thêm 2 tuần để xem trend",
      "C. Phỏng vấn user để hiểu lý do",
      "D. Chọn B và C",
    ],
    3,
    "Cần kết hợp data định lượng (trend) + định tính (user interview).",
  ),
  mcq("test2", "t2-q28",
    'Câu 28: Để đánh giá hiệu quả tính năng "gợi ý sản phẩm" trên trang chủ, nhóm 3 chỉ số nào sau đây là phù hợp nhất?',
    [
      "A. Lượt hiển thị (Impressions), Số lượt chia sẻ (Shares), Thời gian trên trang (Time on Page)",
      "B. Tỷ lệ nhấp (CTR), Tỷ lệ chuyển đổi thành đơn hàng (Conversion Rate), Giá trị đơn hàng trung bình (AOV)",
      "C. Số người dùng mới (New Users), Tổng doanh thu (Gross Revenue), Lượt đánh giá sản phẩm (Product Reviews)",
      "D. Tỷ lệ thoát trang (Bounce Rate), Số lượt xem sản phẩm (Product Views), Tỷ lệ hoàn thành video giới thiệu (Video Completion Rate)",
    ],
    1,
    "CTR + CR + AOV đo trực tiếp đóng góp của gợi ý sản phẩm vào OKR công ty.",
  ),
  // PHẦN 5: BUSINESS ACUMEN/MINDSET
  mcq("test2", "t2-q30",
    "Câu 30: Khi phát triển tính năng mới, yếu tố nào một Product Management cần ưu tiên nhất?",
    [
      "A. Tốc độ ra mắt thị trường",
      "B. Khả năng tạo doanh thu trực tiếp",
      "C. Giải quyết đúng pain point của người dùng",
      "D. Tính khả thi kỹ thuật",
    ],
    2,
    "PM cần hiểu user-centric mindset.",
  ),
  mcq("test2", "t2-q32",
    "Câu 32: Khi phải chọn giữa hai tính năng, bạn dựa vào tiêu chí nào?",
    [
      "A. Số lượng user request nhiều hơn",
      "B. Tính năng align với OKR quý của công ty",
      "C. Đội dev làm nhanh hơn",
      "D. Tính năng competitor đã có",
    ],
    1,
    "Ưu tiên business impact cụ thể, align OKR.",
  ),
  // PHẦN 6: FINTECH
  mcq("test2", "t2-q36",
    'Câu 36: Trong các mô hình Fintech dưới đây, mô hình nào thường cung cấp dịch vụ "Buy Now, Pay Later (BNPL)"?',
    ["A. Digital Lending", "B. WealthTech", "C. RegTech", "D. InsurTech"],
    0,
    "BNPL là một dạng Digital Lending.",
  ),
  mcq("test2", "t2-q37",
    "Câu 37: Một nền tảng cho phép người dùng đóng góp vốn nhỏ để hỗ trợ tài chính cho nhau theo nhóm (group-based lending). Mô hình này thuộc nhóm Fintech nào?",
    [
      "A. Robo-Advisory",
      "B. Crowdfunding",
      "C. Peer-to-Peer Lending",
      "D. BNPL (Buy Now, Pay Later)",
    ],
    2,
    "P2P Lending là mô hình group-based lending.",
  ),
  mcq("test2", "t2-q38",
    'Câu 38: Trong Fintech, "Interchange Fee" thường xuất hiện trong ngữ cảnh nào?',
    [
      "A. Giao dịch P2P (người dùng chuyển tiền cho nhau)",
      "B. Giao dịch qua thẻ giữa người bán và ngân hàng phát hành",
      "C. Vay ngang hàng (P2P Lending)",
      "D. Đầu tư chứng khoán trực tuyến",
    ],
    1,
    "Interchange Fee là phí card network giữa merchant bank và issuer bank.",
  ),
  mcq("test2", "t2-q39",
    "Câu 39: Một ứng dụng đầu tư tài chính cho phép người dùng bắt đầu chỉ với số tiền rất nhỏ. Đâu là mục tiêu chính của đặc điểm sản phẩm này?",
    [
      "A. Tối ưu hóa doanh thu từ nhóm khách hàng cao cấp",
      "B. Đáp ứng yêu cầu pháp lý về bảo vệ nhà đầu tư",
      "C. Giảm rào cản gia nhập cho nhóm người mới hoặc tài chính hạn chế",
      "D. Tăng mức độ phức tạp để giữ chân người dùng lâu hơn",
    ],
    2,
    "Micro-investing nhằm giảm barrier to entry, mở rộng tệp user mới.",
  ),
  // PHẦN 7: TRAVELTECH
  mcq("test2", "t2-q42",
    'Câu 42: Bạn được giao cải thiện tính năng "trip planner" – nơi người dùng tự lên lịch trình du lịch cá nhân. Để quyết định nên ưu tiên cải tiến phần nào, bạn sẽ làm gì trước?',
    [
      "A. So sánh tính năng với các ứng dụng đối thủ",
      "B. Phân tích điểm rơi (drop-off) trong hành trình tạo lịch trình",
      "C. Đánh giá tỷ lệ người dùng sử dụng tính năng qua từng phiên bản app",
      "D. Gửi khảo sát thu thập ý kiến người dùng sau mỗi chuyến đi",
    ],
    1,
    "Drop-off analysis chỉ ra điểm gãy trong hành trình, ưu tiên fix trước.",
  ),
  mcq("test2", "t2-q43",
    "Câu 43: Dữ liệu heatmap cho thấy nhiều người dùng thoát trang ở bước cuối cùng của thanh toán, mặc dù đã chọn xong vé và phòng khách sạn. Giả thuyết nào dưới đây hợp lý nhất? (Chọn nhiều phương án)",
    [
      "A. Người dùng không đủ tiền",
      "B. Quy trình thanh toán quá dài hoặc phức tạp",
      "C. Ứng dụng gặp lỗi backend khi xử lý thanh toán",
      "D. Người dùng không thích giao diện trang thanh toán",
    ],
    [1, 2],
    "Friction trong checkout flow hoặc lỗi backend là 2 root cause phổ biến nhất.",
  ),
  mcq("test2", "t2-q44",
    "Câu 44: Hệ thống phân tích dữ liệu lớn (Big Data) được tích hợp vào các nền tảng travel tech nhằm mục đích nào dưới đây để tối ưu hóa quy trình kinh doanh du lịch?",
    [
      "A. Xây dựng các hợp đồng thông minh (smart contract) cho giao dịch đặt phòng",
      "B. Dự đoán xu hướng du lịch và tối ưu hóa giá vé dựa trên hành vi người dùng",
      "C. Tạo ra các trải nghiệm thực tế ảo (VR) cho các điểm đến du lịch",
      "D. Kết nối các thiết bị IoT để quản lý hành lý tại sân bay",
    ],
    1,
    "Big Data trong travel tech dùng cho demand forecasting và dynamic pricing.",
  ),

  // ===== PHẦN TỰ LUẬN =====
  // PHẦN 1: GENERAL KNOWLEDGE
  text("test2", "t2-q4",
    "Câu 4: Liệt kê 3 Mobile Application của bạn thỏa mãn các điều kiện sau: App bạn thích nhất, App bạn ghét nhất, App bạn dùng nhiều nhất.",
    "Gợi ý: chọn app quen thuộc, dùng hàng ngày. VD: thích = Spotify, ghét = app ngân hàng, dùng nhiều = Facebook/Instagram. Lý do: dễ phân tích, đủ tính năng để nói, không quá niche.",
  ),
  text("test2", "t2-q5",
    "Câu 5: Giả sử bạn là Product Manager của app bạn dùng nhiều nhất, hãy liệt kê 3 đầu việc cụ thể chiếm nhiều thời gian nhất trong 1 sprint điển hình. Mỗi đầu việc gắn với một stakeholder chính và output mong đợi.",
    "Với Instagram: (1) Họp team kỹ thuật ~30% — align với dev về requirements, output: spec/ticket. (2) Báo cáo với sếp ~25% — update tiến độ, xin resource. (3) Nghiên cứu user ~20% — work với data/research, output: insight.",
  ),
  text("test2", "t2-q6",
    "Câu 6: Đối với app bạn thích nhất, chọn 1 tính năng/UX chính khiến bạn yêu thích. Phân tích tác động của tính năng này tới 1 metric quan trọng của App.",
    "VD Spotify — Discover Weekly: không phải tự tìm nhạc mới, app hiểu gu, mỗi tuần có bất ngờ. Metric: Thời gian nghe nhạc mỗi ngày — tăng vì có nhạc mới hay → nghe lâu hơn → ít chuyển app khác.",
  ),
  text("test2", "t2-q7",
    "Câu 7: Nếu bạn được giao cải tiến app bạn ghét nhất, hãy mô tả rõ vấn đề sản phẩm từ góc nhìn người dùng, và đề xuất 1 ý tưởng cải tiến khả thi, gắn với trở ngại về nguồn lực hoặc kỹ thuật.",
    "VD app ngân hàng: vấn đề — chuyển tiền mất 5-6 bước, phức tạp. User bực vì mỗi lần phải nhập lại thông tin người nhận. Ý tưởng: lưu danh bạ người thường xuyên chuyển. Khó khăn kỹ thuật: phải đảm bảo bảo mật. Nguồn lực: team security phải kiểm tra kỹ.",
  ),
  // PHẦN 2: PM/PO
  text("test2", "t2-q8",
    "Câu 8: Hãy liệt kê các team/phòng ban chính mà bạn cần phối hợp khi phát triển 1 tính năng mới trong app bạn thích. Với mỗi nhóm, mô tả ngắn gọn vai trò và output chính mà nhóm đó mang lại.",
    "1. Team Developer — viết code, output: app chạy ổn định. 2. Team Design — wireframe/mockup. 3. Team QA — báo cáo bug. 4. Team Marketing — quảng bá feature qua post, email, banner.",
  ),
  text("test2", "t2-q9",
    "Câu 9: Bạn phụ trách feature mang doanh thu. Data báo revenue tuần trước giảm 10%. Liệt kê 3 giả thuyết (hypothesis) có thể xảy ra dữ liệu hoặc hành vi người dùng. Sau đó mô tả quy trình & dữ liệu bạn sẽ dùng để kiểm chứng từng hypothesis.",
    "1) Lỗi thanh toán — hỏi team kỹ thuật, xem log, phân tích CR ở bước thanh toán. 2) Đối thủ giảm giá — google giá competitor, survey user có chuyển app không, theo dõi churn. 3) App khó dùng (update mới) — xem khiếu nại, so sánh user behavior với tuần trước, phân tích feedback.",
  ),
  text("test2", "t2-q10",
    "Câu 10: Nếu team Dev (Engineer) của bạn từ chối đề xuất bên trên vì họ có ưu tiên khác cao hơn. Liệt kê 2 phương án khả thi kèm theo trade-off về thời gian/kỹ thuật. Sau đó chọn 1 phương án tối ưu và giải thích vì sao.",
    "Cách 1: Làm từng phần nhỏ — chia 3 lần, lâu hơn (3 tháng vs 1) nhưng dễ làm, ít rủi ro. Cách 2: Làm đơn giản trước — version cơ bản, nhanh hơn (2 tuần) nhưng tech debt, ít tùy chọn advanced. → Chọn cách 1 vì tốt hơn lâu dài, dev cũng dễ chấp nhận hơn.",
  ),
  text("test2", "t2-q11",
    "Câu 11: Nếu cho phép bạn xóa khỏi ứng dụng 1 tính năng nào đó, bạn sẽ xóa tính năng nào? Tại sao?",
    "VD App Ngân hàng — xóa: màn hình xem điểm thưởng. Vì ít người dùng (chỉ 10% user xem), confusing (user không hiểu sao có điểm), tốn công maintain code. Xóa xong: app đơn giản hơn, focus vào chức năng chính.",
  ),
  text("test2", "t2-q12",
    "Câu 12: Bạn dùng nhiều nhất tính năng nào? Mô tả ngắn gọn hành vi sử dụng điển hình.",
    "VD Instagram — Xem Stories của bạn bè. Mỗi ngày 4-5 lần, mỗi lần 5-10 phút, chủ yếu lúc nghỉ giải lao.",
  ),
  text("test2", "t2-q13",
    "Câu 13: Theo bạn Success Metric của tính năng này là gì? Giải thích vì sao lại phù hợp.",
    "Thời gian xem Stories mỗi ngày. Lý do: xem lâu = user thích content → quay lại app nhiều → Instagram kiếm tiền từ quảng cáo nhiều hơn.",
  ),
  // PHẦN 3: UX/UI
  text("test2", "t2-q14",
    "Câu 14: Quy trình UX Design cơ bản gồm những bước nào? Sắp xếp trình tự các bước trong quy trình UX Design.\n\nA. Tối ưu hóa (Iteration)\nB. Nghiên cứu (Research)\nC. Phân tích dữ liệu (Analysis)\nD. Kiểm thử với người dùng (Testing)\nE. Thiết kế ý tưởng (Ideation)",
    "Đáp án đúng: B → C → E → D → A (Research → Analysis → Ideation → Testing → Iteration).",
  ),
  text("test2", "t2-q20",
    'Câu 20: Sắp xếp các bước sau để tạo thành giải pháp "Minh bạch & Hỗ trợ tức thì":\n1. Bổ sung nút "Xem chi tiết" dẫn đến timeline từng bước xử lý.\n2. Cho phép gửi yêu cầu hỗ trợ nhanh (hotline/chat) nếu quá thời gian SLA.\n3. Kiểm tra trạng thái giao dịch (transaction status) ngay khi user mở app.\n4. Thu thập feedback: "Bạn có hài lòng với thông tin giao dịch?"\n5. Hiển thị cảnh báo "Đang xử lý" với thanh tiến trình.\n6. Tối ưu lại UI timeline dựa trên mức độ ưu tiên thông tin.\n7. Tích hợp chat bot AI để trả lời tự động "Tại sao trễ" & "Bao lâu nữa?".\n8. Gửi push notification cho cả A và B khi giao dịch hoàn tất.',
    "Quy trình gợi ý: 3 → 5 → 1 → 8 → 7 → 2 → 4 → 6.",
  ),
  text("test2", "t2-q21",
    'Câu 21: Sắp xếp các bước sau để tạo thành giải pháp "Phòng ngừa & Tái tương tác":\n1. Với B, gửi email/SMS thông báo "Bạn sẽ nhận tiền khoảng xx:xx".\n2. Nếu quá thời gian dự kiến, tự động roll-back (hoàn tiền tạm thời).\n3. Cung cấp mục "Lịch sử giao dịch chậm" để user dễ xem lại.\n4. Thông báo rollback cho A và đề nghị "Thử lại" hoặc "Chờ tiếp".\n5. Trước khi trừ tiền, hiển thị chi tiết phí, thời gian dự kiến.\n6. Phân tích dữ liệu chậm để tối ưu API & UI confirmation.\n7. Gửi survey ngắn: "Bạn có gặp khó khăn khi giao dịch không?"\n8. Xác nhận lại với user A: "Bạn có chắc muốn chuyển?" với tóm tắt ETA.',
    "Gợi ý sắp xếp theo flow phòng ngừa → tái tương tác: 5 → 8 → 1 → 2 → 4 → 3 → 7 → 6.",
  ),
];

const seed: Question[] = [...seedTest1, ...seedTest2];

type QuizState = {
  questions: Question[];
  addQuestion: (q: Omit<Question, "id">) => void;
  updateQuestion: (id: string, q: Omit<Question, "id">) => void;
  deleteQuestion: (id: string) => void;
};

export const useQuizStore = create<QuizState>((set) => ({
  questions: seed,
  addQuestion: (q) =>
    set((state) => ({
      questions: [...state.questions, { ...q, id: crypto.randomUUID() } as Question],
    })),
  updateQuestion: (id, q) =>
    set((state) => ({
      questions: state.questions.map((existing) =>
        existing.id === id ? ({ ...q, id } as Question) : existing,
      ),
    })),
  deleteQuestion: (id) =>
    set((state) => ({
      questions: state.questions.filter((q) => q.id !== id),
    })),
}));
